# Generated by Django 5.2.7 on 2025-11-04 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('student_code', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('date_of_pretest', models.DateField()),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('vo2_max', models.FloatField(blank=True, null=True)),
                ('flexibility_cm', models.FloatField()),
                ('strength_reps', models.FloatField()),
                ('agility_sec', models.FloatField()),
                ('speed_sec', models.FloatField()),
                ('endurance_min', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
